### ISSUE TITLE
Error on Registration

### ISSUE THREAD

**Issue by hendisantika** [gustavoponce7/SpringSecurityLoginTutorial#5]
Hi Gustavo,

I tried your repo. But I have an issue when trying to register my account.

```
Thu Jun 15 10:07:30 WIB 2017
There was an unexpected error (type=Internal Server Error, status=500).
could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

-------

com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'role_id' cannot be null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_121]
```

Do you have any solution?

Thanks

**Comment by hendisantika** [comment]
Sorry, I have found the issue.
The SQL Script is not executed by Spring Boot.

So, I tried to run script manually. Then It goes OK and runs well.

Thanks you.
